# Font
font_size 22
font_family                    Fira Code
bold_font                      Fira Code Bold
italic_font                    Fira Code
bold_italic_font               Fira Code Bold
font_features                  Fira-Code +calt +ss01 +ss02 +ss05 +cv06
font_features                  Fira-Code-Bold +calt +ss01 +ss02 +ss05 +cv06
symbol_map U+23FB-U+23FE,U+2665,U+26A1,U+2B58,U+E000-U+E00A,U+E0A0-U+E0A3,U+E0B0-U+E0D4,U+E200-U+E2A9,U+E300-U+E3E3,U+E5FA-U+E6AA,U+E700-U+E7C5,U+EA60-U+EBEB,U+F000-U+F2E0,U+F300-U+F32F,U+F400-U+F4A9,U+F500-U+F8FF,U+F0001-U+F1AF0 Symbols Nerd Font Mono
# -> != >=
disable_ligatures cursor

# Window
hide_window_decorations        titlebar-only
window_padding_width           7
# remember_window_size           yes

# Tab bar
tab_bar_edge                   top
tab_bar_style                  powerline
tab_powerline_style            slanted

# General key mapping
macos_option_as_alt yes

# Extra
enable_audio_bell no
scrollbar never
pixel_scroll no
cursor_shape block
cursor_blink_interval 0
cursor_trail 3
cursor_trail_decay 0.1 0.4

# Theme switching
map ctrl+cmd+shift+m kitten themes --reload-in=all Catppuccin Kitty Mocha
map ctrl+cmd+shift+t kitten themes

# Change Editor
editor /opt/homebrew/bin/nvim

# Use Fish Shell
shell /opt/homebrew/bin/fish


# BEGIN_KITTY_THEME
# Catppuccin Kitty Mocha
include current-theme.conf
# END_KITTY_THEME
