# =========================
# Global
# =========================
add_newline = true
command_timeout = 800

format = """
$custom\
$directory\
$git_branch\
$git_status
$character
"""

# =========================
# Custom prefix: icon
# =========================
[custom.icon]
command = "echo 󰘧"
when = "true"
style = "bold red"
format = "[$output]($style) "

# =========================
# Custom prefix: Core
# =========================
[custom.core]
command = "echo "
when = "true"
style = "bold bright-yellow"
format = "[$output]($style)"

# =========================
# Prompt character
# =========================
[character]
success_symbol = "[>](bold yellow)"
error_symbol   = "[>](bold red)"

# =========================
# Directory
# =========================
[directory]
style = "cyan"
truncation_length = 3
truncate_to_repo = true
truncation_symbol = "…/"
read_only = " "

# =========================
# Git branch
# =========================
[git_branch]
symbol = " "
style = "bold purple"
format = " [$symbol$branch]($style)"

# =========================
# Git status (identical symbols)
# =========================
[git_status]
style = "yellow"
format = " [$all_status$ahead_behind]($style)"

staged     = "+${count}"
modified   = "!${count}"
untracked  = "?${count}"
deleted    = "✘${count}"
renamed    = "»${count}"
conflicted = "=${count}"
stashed    = "⚑${count}"

ahead     = " ↑${count}"
behind    = " ↓${count}"
diverged  = " ↑${ahead_count}↓${behind_count}"

# =========================
# Disable noise
# =========================
[cmd_duration]
disabled = true

[jobs]
disabled = true

[package]
disabled = true
