# TokyoNight-inspired base background
background #16161e

# Foreground
foreground #c0caf5

# Optional: force cursor color
cursor #7dcfff

# Shades
color0  #1a1b26
color8  #414868

# Reds
color1  #f7768e
color9  #ff899d

# Greens
color2  #9ece6a
color10 #9fe044

# Yellows
color3  #e0af68
color11 #faba4a

# Blues
color4  #7aa2f7
color12 #8db0ff

# Magentas
color5  #bb9af7
color13 #c7a9ff

# Cyans
color6  #7dcfff
color14 #a4daff

# Whites / Foreground
color7  #a9b1d6
color15 #c0caf5
